In [1]:
#Q1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

arr = np.random.randint(1, 101, size=(3, 3))

interchanged_arr = arr.T

print("Original Array:")
print(arr)
print("\nInterchanged Array:")
print(interchanged_arr)


Original Array:
[[54 65 73]
 [67 71 93]
 [12  6 97]]

Interchanged Array:
[[54 67 12]
 [65 71  6]
 [73 93 97]]


In [2]:
#Q2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

import numpy as np

arr = np.arange(10)

arr_2x5 = arr.reshape(2, 5)
arr_5x2 = arr.reshape(5, 2)

print("Original Array:")
print(arr)
print("\n2x5 Array:")
print(arr_2x5)
print("\n5x2 Array:")
print(arr_5x2)

Original Array:
[0 1 2 3 4 5 6 7 8 9]

2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [3]:
#Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

arr = np.random.rand(4, 4)

bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print("Original Array:")
print(arr)
print("\nBordered Array:")
print(bordered_arr)


Original Array:
[[0.36968624 0.05830414 0.39553181 0.37522748]
 [0.20377699 0.71068911 0.04444036 0.84528839]
 [0.05009431 0.73994004 0.33675488 0.95740125]
 [0.19040874 0.66645052 0.58771548 0.54708405]]

Bordered Array:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.36968624 0.05830414 0.39553181 0.37522748 0.        ]
 [0.         0.20377699 0.71068911 0.04444036 0.84528839 0.        ]
 [0.         0.05009431 0.73994004 0.33675488 0.95740125 0.        ]
 [0.         0.19040874 0.66645052 0.58771548 0.54708405 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
#Q4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

import numpy as np

arr = np.arange(10, 61, 5)

print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


In [5]:
#Q5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

arr = np.array(['PythOn', 'nUmPy', 'PandaS'])

uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)

print("Original Array:")
print(arr)
print("\nUppercase Array:")
print(uppercase_arr)
print("\nLowercase Array:")
print(lowercase_arr)
print("\nTitlecase Array:")
print(titlecase_arr)


Original Array:
['PythOn' 'nUmPy' 'PandaS']

Uppercase Array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
['python' 'numpy' 'pandas']

Titlecase Array:
['Python' 'Numpy' 'Pandas']


In [ ]:
#6.Generate a NumPy array of words. Insert a space between each character of every word in the array.
import numpy as np
a=np.array(['hello', 'world', 'numpy', 'array'])
for word in a:
    spaced_word = ' '.join(word)
    print(spaced_word)




h e l l o
w o r l d
n u m p y
a r r a y


In [ ]:
#7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
addition=a+b
subtraction=a-b
multiplication=a*b
division=a/b
print(a)
print(b)
print("Addition of array:\n",addition)
print("Subtraction of arrays:\n",subtraction)
print("Multiplication of two 2d arrays:\n",multiplication)
print("Division of two 2d arrays:\n",division)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
Addition of array:
 [[ 8 10 12]
 [14 16 18]]
Subtraction of arrays:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication of two 2d arrays:
 [[ 7 16 27]
 [40 55 72]]
Division of two 2d arrays:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [ ]:
#8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
import numpy as np
a=np.eye(5)
print(a)
print("Diagonal elements:\n",np.diag(a))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal elements:
 [1. 1. 1. 1. 1.]


In [ ]:
#9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
import numpy as np
a=np.random.randint(0,1000,100)
print(a)
for i in a:
    if i>1:
        for j in range(2,i):
            if i%j==0:
                break
        else:
            print(i,end=' ')


[485 295 816  15 534 175 165 248   9 444 297 843 182   2 402 973 366 387
 158 372  67 984 498  44 801 929 418 689 370 123 463  90 408 248 225 281
 575  99 668 978 878 882 534 439 834  72 179 826  12 684 126  85 445 687
 895 256 409 603 844 639  16 271 764 158 490 991 605 543 784 465  67  99
 993 554 938 947 106 900 163 822 398 758 457 187 618  31 654 675 795 160
 302 937 241 718 252 533 464  48   4 789]
2 67 929 463 281 439 179 409 271 991 67 947 163 457 31 937 241 

In [ ]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
import numpy as np
daily_temperature = np.random.randint(22, 25, 28)
print("Daily Temperatures:", daily_temperature)
weekly_temperatures = daily_temperature.reshape(-1, 7)
print(weekly_temperatures)
weekly_average = np.mean(weekly_temperatures, axis=1)
print("Weekly Averages:", weekly_average)
overall_average = np.mean(daily_temperature)
print("Overall Monthly Average:", overall_average)


Daily Temperatures: [24 22 23 22 22 24 24 23 23 22 24 22 23 24 23 22 22 22 22 22 23 24 22 23
 24 24 22 24]
[[24 22 23 22 22 24 24]
 [23 23 22 24 22 23 24]
 [23 22 22 22 22 22 23]
 [24 22 23 24 24 22 24]]
Weekly Averages: [23.         23.         22.28571429 23.28571429]
Overall Monthly Average: 22.892857142857142
